name = "DeepRecurrentEncoder"
uuid = "81cdbb96-0126-4941-b8f1-96022f2db8f3"
authors = ["Benedikt V. Ehinger"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
