







print("1")





print("2")











1\.Learning rate

- Too high a learning rate might cause the model to oscillate or even diverge during training, leading to poor convergence. This could result in poor quality of the graphics generated by the autoencoder, with significant loss of detail.
- Too low a learning rate might lead to excessively slow training and the model might get stuck in local minima. This could cause the autoencoder to generate overly smooth images that miss some important features.

2\. Epoch Number

- Too few epochs might prevent the model from adequately learning the features in the data, affecting the quality and accuracy of the reconstructed graphics.
- Too many epochs might lead to overfitting where the model performs well on the training data but poorly on new, unseen data. An overfitted autoencoder might generate images that are too reliant on specific noise and details of the training data, instead of learning a more general representation of the data.

3\. Batch Size

- Smaller batch sizes generally provide a more accurate gradient estimation but might lead to a less stable training process and longer training times. Smaller batches might enable the model to learn more details, potentially leading to better performance in image reconstruction tasks.
- Larger batch sizes can speed up training and stabilize gradient estimations but may reduce the generalization ability of the model during training. In autoencoders, too large a batch might result in reconstructed images that lack detail and appear more blurred or smooth.











**Change Epo Number**

#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=30,lr=0.05,batch\_size=128)# |> CuArray)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.001.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.002.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.003.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.004.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.005.png)






#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.05,batch\_size=128)# |> CuArray)

![ref1]![ref2]

![ref3]![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.009.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.010.png)












#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=200,lr=0.05,batch\_size=128)# |> CuArray)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.011.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.012.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.013.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.014.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.015.png)








**Change LR**

#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.01,batch\_size=128)# |> CuArray)


![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.016.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.017.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.018.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.019.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.020.png)










#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.05,batch\_size=128)# |> CuArray)

![ref1]![ref2]

![ref3]![ref4]

![ref5]














#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.1,batch\_size=128)# |> CuArray)


![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.023.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.024.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.025.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.026.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.027.png)




**Change batch-size**

#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.05,batch\_size=64)# |> CuArray)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.028.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.029.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.030.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.031.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.032.png)




#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.05,batch\_size=128)# |> CuArray)

![ref1]![ref2]

![ref3]![ref4]

![ref5]










#dre,ps, st = fit(DRE, Float32.(data))# |> CuArray)

dre,ps, st = fit(DRE, Float32.(data[:,1:end÷2\*2,:])|> x->use\_gpu ? CuArray(x) : x,f,evts;n\_epochs=100,lr=0.05,batch\_size=256)# |> CuArray)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.033.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.034.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.035.png)![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.036.png)

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.037.png)






Task 1. Plot change in R² for each predicted value from all 42 channels.

Semi partial R²

![](Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.038.png)

Sub Task, check dimension of y\_pred and y\_data
R² check the variability between the data

Task 2 : use make.jl file to create the document
Install life server to check the changes done at the same time.








[ref1]: Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.006.png
[ref2]: Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.007.png
[ref3]: Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.008.png
[ref4]: Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.021.png
[ref5]: Aspose.Words.efcefd3e-a8ce-4538-accf-1b4b8b28d44b.022.png
